article: https://www.hackster.io/jakub-smejkal/wireless-presenter-with-accelerometer-962318
video: https://youtu.be/OCPPKXzCBg0
images:
  - title:
    url: https://cdn.myshoptet.com/usr/shop.hardwario.com/user/shop/category_portrait/156-2_button-kit-a1.jpg?5de56e1c
assembly:
  - name: BigClown Button Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module
